feat(FeedbackForm): add adaptivity  for FeedbackForm
consta-design-system/analytic-ui pull request #4
Opened 2021-12-13 15:55 UTC by N1MBER

closes[ #1695](https://github.com/gazprom-neft/consta-uikit/issues/1695)

Добавлен адаптив для компонента FeedbackForm

2021-12-14 12:13 UTC, N1MBER commented
Посмотреть изменение разрешения вне мобильного инструмента

2022-01-20 12:46 UTC, gizeasy requested changes

2022-01-20 12:46 UTC, gizeasy commented on yarn.lock
> +"@babel/runtime@^7.0.0", "@babel/runtime@^7.4.2", "@babel/runtime@^7.4.5", "@babel/runtime@^7.5.0":
А зачем изменения в  yarn.lock?

2022-01-20 12:46 UTC, gizeasy commented on .stylelintrc.js
> -    'order/properties-order': [
Зачем правила убрал?

2022-01-20 12:46 UTC, gizeasy commented on package.json
> +    "deps": "yarn install & yarn add @emotion/styled-base@10 -D"
`prepare` и  `deps` можно уже грохнуть
проблема решилась после того как из peerDependencies убрали не нужные зависимоти

2022-01-20 12:46 UTC, gizeasy commented on src/__private__/storybook/components/RemadeInfo/RemadeInfo.tsx
> +import { Informer } from '@consta/uikit/Informer';
а что у тебя настройки так сильно поменялись что `;` появилось?

2022-01-24 11:07 UTC, closed without merging